"""Names of input data columns.
"""

CLINICAL_TRIALS_ID_COLUMN_NAME = "id"
CLINICAL_TRIALS_TITLE_COLUMN_NAME = "scientific_title"
CLINICAL_TRIALS_DATE_COLUMN_NAME = "date"
CLINICAL_TRIALS_JOURNAL_COLUMN_NAME = "journal"

DRUGS_ATCCODE_COLUMN_NAME = "atccode"
DRUGS_NAME_COLUMN_NAME = "drug"

PUBMED_ID_COLUMN_NAME = "id"
PUBMED_TITLE_COLUMN_NAME = "title"
PUBMED_DATE_COLUMN_NAME = "date"
PUBMED_JOURNAL_COLUMN_NAME = "journal"
